<a href="https://colab.research.google.com/github/Voinruslan2000/Calculator.java/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22New_Notebook%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# b
array = np.zeros(10)
print(array,'\n')
# c
array_1 = np.ones(10)
print(array_1,'\n')
# d
array_5 = np.ones(10)*5
print(array_5,'\n')
# e
a=np.arange(10,51)
print(a,'\n')
# f
a=np.arange(10,51,2)
print(a,'\n')
# g Создать матрицу 3х3 с числами от 0 до 8
a = np.arange(9).reshape(3,3)
print(a,'\n')
# Создать единичную матрицу 3x3
a = np.eye(3)
print(a)

# i.Используйте NumPy для генерации случайного числа от 0 до 1
a = np.random.rand(1)
print(a)

# j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
a = np.random.randn(25)
print(a)

# k.Создайте следующую матрицу используя функции библиотеки NumPy
a = np.arange(0.01,1.01, 0.01).reshape(10,10)
print(a)

# l.Дана стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat,'\n')
print(mat[2:5,1:5])

# m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l
mat = np.arange(1,26).reshape(5,5)
print(mat,'\n')
print(mat[3,4])

# n.Написать код к стартовой матрице задачи l
print(mat[0:3,1:2])

# o.Написать код к стартовой матрице задачи l
print(mat[4:])

# p.Написать код к стартовой матрице задачи l
print(mat[3:])

#  q.Получить сумму всех значений в стартовой матрице mat
print(np.sum(a))

# r.Получить стандартное отклонение в стартовой матрице mat
print(np.std(mat))

# s.Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.33890694]
[ 1.60500066  1.16269187 -0.22920728  0.536158    1.5695648   0.50448849
 -0.19003511  0.67911186 -0.71422378 -0.56965839 -0.89146001 -0.12426794
 -0.66419735  1.3637093  -0.2442915  -0.2482129   0.08856199 -0.11824323
 -0.23775769 -0.32716872 -0.1303088  -0.15655752  0.50125662  0.51127165
  2.46017784]
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]